// Code generated by "stringer -type=TabletopSimulatorResponseMessageId"; DO NOT EDIT.

package tts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN_RESPONSE - -1]
	_ = x[NEW_OBJECT_RESPONSE-0]
	_ = x[GAME_LOADED_RESPONSE-1]
	_ = x[PRINT_RESPONSE-2]
	_ = x[ERROR_RESPONSE-3]
	_ = x[CUSTOM_RESPONSE-4]
	_ = x[RETURN_RESPONSE-5]
	_ = x[GAME_SAVED_RESPONSE-6]
	_ = x[OBJECT_CREATED_RESPONSE-7]
}

const _TabletopSimulatorResponseMessageId_name = "UNKNOWN_RESPONSENEW_OBJECT_RESPONSEGAME_LOADED_RESPONSEPRINT_RESPONSEERROR_RESPONSECUSTOM_RESPONSERETURN_RESPONSEGAME_SAVED_RESPONSEOBJECT_CREATED_RESPONSE"

var _TabletopSimulatorResponseMessageId_index = [...]uint8{0, 16, 35, 55, 69, 83, 98, 113, 132, 155}

func (i TabletopSimulatorResponseMessageId) String() string {
	i -= -1
	if i < 0 || i >= TabletopSimulatorResponseMessageId(len(_TabletopSimulatorResponseMessageId_index)-1) {
		return "TabletopSimulatorResponseMessageId(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _TabletopSimulatorResponseMessageId_name[_TabletopSimulatorResponseMessageId_index[i]:_TabletopSimulatorResponseMessageId_index[i+1]]
}
